### ISSUE TITLE
Typo in release title

### ISSUE THREAD

**Issue by gewarren** [microsoft/MicrosoftTeamsHealthcareBotApplication#1]
@arieschwartzman - can you update the title of the release from "Microsift" to "Microsoft"? See https://github.com/MicrosoftDocs/feedback/issues/2921.

**Comment by rootsmusic** [comment]
@gewarren The doc is not found.

**Comment by gewarren** [comment]
Hmm, deleted on July 1 in [this commit](https://github.com/MicrosoftDocs/samples/pull/2375/commits/40c9e6da7500470271bb6c0630afb0a5fd435a50). @arieschwartzman was that expected? We had some of our dotnet samples disappear too. cc @MSshujia

**Comment by gewarren** [comment]
It looks like that sample was intentionally deleted based on https://github.com/MicrosoftDocs/samples/blob/master/Microsoft/microsoftteamshealthcarebotapplication/.samples-status.json. I'll close this issue.

**Comment by daxianji007** [comment]
Yes, a valid sample should have a yaml front-matter in the readme.md
